# Generated by Django 4.0.2 on 2022-03-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homechefapp', '0006_newuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
