# Generated by Django 4.0.2 on 2022-04-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homechefapp', '0007_alter_profile_image_delete_newuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
