# Generated by Django 4.0.2 on 2022-05-11 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homechefapp', '0010_alter_comment_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recipe_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 11, 7, 2, 261381)),
        ),
    ]
