# Generated by Django 4.0.2 on 2022-05-11 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homechefapp', '0014_comment_recipe_name_alter_comment_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='recipe_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 14, 30, 4, 355084)),
        ),
    ]
