# Generated by Django 4.0.2 on 2022-05-11 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homechefapp', '0015_rename_recipe_name_comment_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 14, 58, 1, 434644)),
        ),
    ]
